on:
  workflow_dispatch:
    inputs:
      publish_version:
        description: 'Publish version'
        required: true
        default: 'major' 
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  build:
    runs-on: ubuntu-latest
    if:  ${{ inputs.publish_version }} 
    strategy:
      matrix:
        node-version: [18.x]  

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    
    - run: npm run build --if-present
    - run: git config user.email "122662496+DubiousArk@users.noreply.github.com"
    - run: git config user.name "DubiousArk"
#     - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
#     - run: git config user.name "github-actions[bot]"
 
    - run: npm version ${{ inputs.publish_version }}
    
    - run: git push --tags
    
    - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
    - run: echo "//registry.npmjs.org/:always-auth=true" >> ~/.npmrc
    - run: npm publish
    
#     - run: git push https://${{ secrets.TOKEN }}@github.com/DubiousArk/from-dublin.git

